apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:r8YRsjHl/PSBWImFBgyk7kCbA22SyT1ErgiJ9Pm2Cb8=,iv:C0kOoIthSbUKHl3TiqJ20dHU5wtHF8A/phTjnP69UNA=,tag:vXPXK7W25FERFl89n983Ag==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16se9j6rfs2m3ckxdv3avlf0s4den9nc2qjfr7fptvf4hqpyysgpsrd056v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpYmNlZjZZTTV2Q3NSaHZJ
            cVREdFhwNEFBSGt5UGxWUVRqeTJVRlZOQ3c4CjM1bFkvSExIcWNMV0NzMytaVnUr
            Wml3M1RJaXZ2aGwzS2R2TDhUbGZ2NWcKLS0tIEEwZEgvQ3BmTGoyOGYzY0xmVUpW
            bHdjazNIQ2dnclFrVTNOeXcyYlBCcFUKDVSI40gIQVtwOx3+xoAXB94WTavgl2JL
            xH2e9JAmQIHjcKk0PKSfb/ChBfEVH7p3GGP40OGL9KES7BpvQR06TQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-10T20:39:09Z"
    mac: ENC[AES256_GCM,data:OuUCTbUW0gO6Vy0gZK1mRgiYMvTStgRS+LORuJ+YUSBFJH9mgX2e36k5JHTjqyutc/zLXnGp3dB8X9WF4YtgjxWkyk6V59E2fgD8Z4t3l1r+k/QIUOnK/WIT3rS5UIApZf/No+IVqXUWyYIEIt3hNwYvGG11TJHNgwGKpg30zQQ=,iv:DTtLjWvODGHGX5SUoE6t8dnMphBCkDcqjDoSV/pPLKA=,tag:dJCm9KqrjlhPoACdOe+KGQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
