apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:pYRsTQfPFRlBrsJZf58dQpU55jCV2dxhM0L5NoYGHfg=,iv:/oK/z5ZTawZksGleJbLmsZ3ZCrdokFFDNgCxyWQvNyc=,tag:aSkspPmNVueT7YkxbJ50Qw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16se9j6rfs2m3ckxdv3avlf0s4den9nc2qjfr7fptvf4hqpyysgpsrd056v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTOUVlMk9VSDR4c0U1S3lQ
            ZEFISEs1cjFSOHZWU3poTFhGbDBJaWFucFIwCkRUTDd0YmRYWFc5MVlOTEtIaXVS
            aVcrNmJYUjI2ckY4RUluT2gvNXk4eG8KLS0tIGR5b295R25IdHZEbldsZEN1YU96
            cXZHeXd5Z3ZjektKSERSOUdyNEdWeW8KHxm6no+JxI+zptRUKjZrubWiSCW5Bi90
            /mltmCcmAP21sGhu4JZb3nrQR0o1UsUFW2DW6DddsNcwc+6PmlQRBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-10T20:05:16Z"
    mac: ENC[AES256_GCM,data:FWS4FQKtWm1fKgSN+5xFIMlptiIp9Db/iJ5MxbnAOvFubRlCzSaH50u3/Y9J1Snqu4JMmP6as8JWvF6jv0Ngb0pK8b6QN3Tk2oGmbbZJNedNGSZAlK2tSVdo4IKNutb7N8Lnj+rlZUg8EIJ/Bjj9kfVxyU1bj5FmbqSd49VvUiQ=,iv:R70tgAIww77PauS5BtwUTDJcWPE+yWSWkZ0ftzTGyVo=,tag:CWs/SWPcpvKoHkwjeuik7g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
